version: '2'


services:
    storage:
        image: storage:1.0
        expose:
            - "8081"
            - "9000"
        ports:
            - "8081:8081"
        stdin_open: true
        restart: always
        networks:
            dockernet:
                ipv4_address: 172.16.2.10
        depends_on:
            - kafka
    engine:
        image: engine:1.0
        expose:
            - "8085"
            - "9000"
        ports:
            - "8085:8085"
        stdin_open: true
        restart: always
        networks:
              dockernet:
                  ipv4_address: 172.16.2.11
        depends_on:
            - kafka
    service:
        image: service:1.0
        expose:
            - "8082"
            - "9000"
        ports:
            - "8082:8082"
        stdin_open: true
        restart: always
        networks:
            dockernet:
                ipv4_address: 172.16.2.12
        depends_on:
            - kafka
    rules:
        image: rules:1.0
        expose:
            - "8083"
            - "9000"
        ports:
            - "8083:8083"
        stdin_open: true
        restart: always
        networks:
            dockernet:
                ipv4_address: 172.16.2.13
        depends_on:
            - kafka

    mqtt:
        image: mqtt:1.0
        expose:
            - "8084"
            - "9000"
        ports:
            - "8084:8084"
        stdin_open: true
        restart: always
        networks:
            dockernet:
                ipv4_address: 172.16.2.14
        depends_on:
            - kafka

    management:
        image: management:1.0
        expose:
            - "8086"
            - "9000"
        ports:
            - "8086:8086"
        stdin_open: true
        restart: always
        networks:
            dockernet:
                ipv4_address: 172.16.2.14
        depends_on:
            - kafka

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - "2181:2181"
        networks:
            - dockernet
    kafka:
        build: kafka/
        ports:
          - "9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 192.168.2.3
#          KAFKA_ADVERTISED_HOST_NAME: 192.168.1.22
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "v1.data:1:1,v1.command:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - dockernet
        depends_on:
            - zookeeper

networks:
    dockernet:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.16.2.0/24
              gateway: 172.16.2.1
